"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lab4_js_1 = require("./lab4.js");
var DocType = lab4_js_1.Transport.DocType;
var BodyType = lab4_js_1.Transport.BodyType;
var CarClass = lab4_js_1.Transport.CarClass;
var Owner = lab4_js_1.Transport.Owner;
var Car = lab4_js_1.Transport.Car;
var Motorbike = lab4_js_1.Transport.Motorbike;
var VehicleStorage = lab4_js_1.Transport.VehicleStorage;
var owner = new Owner("Иванов", "Иван", "Иванович", new Date(1980, 1, 1), DocType.PASSPORT, "1234", "567890");
var car = new Car("Toyota", "Corolla", 2015, "12345678901234567", "A123BC", owner, BodyType.SEDAN, CarClass.COMFORT);
var motorbike = new Motorbike("Yamaha", "YZF-R1", 2020, "98765432109876543", "M123XY", owner, "Стальная", true);
var vehicleStorage = new VehicleStorage();
vehicleStorage.save(car);
vehicleStorage.save(motorbike);
console.log(owner.printOwnerInfo());
console.log(car.printVehicleInfo());
console.log(motorbike.printVehicleInfo());
vehicleStorage.getAll().forEach(function (vehicle) { return console.log(vehicle.printVehicleInfo()); });
